/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Admin;

import BUS.ChamCongAdminBUS;
import BUS.ChamCongBUS;
import BUS.LuongBUS;
import BUS.NhanVienBUS;
import BUS.PhongBanBUS;
import Model.ChamCong;
import Model.ChamCongAdmin;
import Model.Luong;
import Model.NhanVien;
import Model.PhongBan;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class QLChamCongPanel extends javax.swing.JPanel {

    private PhongBanBUS pbBUS = new PhongBanBUS();
    private ChamCongAdminBUS chamCongAdminBUS = new ChamCongAdminBUS();
    private ChamCongBUS chamCongBUS = new ChamCongBUS();
    private DefaultTableModel model = new DefaultTableModel();
    private NhanVienBUS nhanvienBUS = new NhanVienBUS();
    private LuongBUS luongBUS = new LuongBUS();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    public QLChamCongPanel() {
        initComponents();
        KhoiTaoDuLieu();
        KhoiTaoCBO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNgayChamCong = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboPhongBan = new javax.swing.JComboBox();
        btnLoc = new javax.swing.JButton();
        chkTimKiemNgay = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPhongBan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNgayLam = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        lblLuongCB = new javax.swing.JLabel();
        lblLuongTL = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnXuatExcel = new javax.swing.JButton();
        btnXuatPDF = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChamCong = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        lblSoCongLam = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblThuong = new javax.swing.JLabel();

        jLabel1.setText("Ngày:");

        jLabel2.setText("Phòng Ban:");

        cboPhongBan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        chkTimKiemNgay.setText("Lọc theo ngày");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chkTimKiemNgay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnLoc)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkTimKiemNgay)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLoc, cboPhongBan, jLabel1, jLabel2, txtNgayChamCong});

        jLabel3.setText("Mã Nhân Viên:");

        lblMaNV.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setText("Tên Nhân Viên:");

        lblTenNV.setForeground(new java.awt.Color(255, 0, 0));

        jLabel5.setText("Phòng Ban:");

        lblPhongBan.setForeground(new java.awt.Color(255, 0, 0));

        jLabel6.setText("Ngày Làm:");

        jLabel7.setText("Trạng Thái: ");

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Lương Cơ Bản:");

        lblLuongCB.setForeground(new java.awt.Color(255, 0, 0));

        lblLuongTL.setForeground(new java.awt.Color(255, 0, 0));

        jLabel9.setText("Lương Thực Lãnh:");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnXuatExcel.setText("Xuất Excel");

        btnXuatPDF.setText("Xuất PDF");

        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnSua)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addGap(18, 18, 18)
                .addComponent(btnXuatExcel)
                .addGap(18, 18, 18)
                .addComponent(btnXuatPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLamMoi)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLamMoi, btnSua, btnThem, btnXoa, btnXuatExcel, btnXuatPDF});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLamMoi, btnSua, btnThem, btnXoa, btnXuatExcel, btnXuatPDF});

        tblChamCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblChamCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChamCongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChamCong);

        jLabel10.setText("Số Công Làm:");

        lblSoCongLam.setForeground(new java.awt.Color(255, 0, 0));

        jLabel11.setText("Thưởng:");

        lblThuong.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayLam, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblLuongCB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblLuongTL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoCongLam, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtNgayLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLuongCB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoCongLam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblThuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblLuongTL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void tblChamCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChamCongMouseClicked
        int row = tblChamCong.getSelectedRow();
        if (row >= 0) {
            // Lấy dữ liệu từ JTable theo vị trí cột như trong KhoiTaoDuLieu()
            String maCC = tblChamCong.getValueAt(row, 0).toString();
            String maNV = tblChamCong.getValueAt(row, 1).toString();
            String hoTen = tblChamCong.getValueAt(row, 2).toString();
            String phong = tblChamCong.getValueAt(row, 3).toString();
            Date ngayLam = (Date) tblChamCong.getValueAt(row, 4);
            String trangThai = tblChamCong.getValueAt(row, 5).toString();
            Object luongCBObj = tblChamCong.getValueAt(row, 6);
            Object thucLinhObj = tblChamCong.getValueAt(row, 7);
            Object tongKhauTruObj = tblChamCong.getValueAt(row, 8);
            Object tongThuNhapObj = tblChamCong.getValueAt(row, 9);
            lblMaNV.setText(maNV);
            lblTenNV.setText(hoTen);
            lblPhongBan.setText(phong);
            txtNgayLam.setDate(ngayLam);
            cboTrangThai.setSelectedItem(trangThai);

            DecimalFormat dfTien = new DecimalFormat("#,###");

            lblLuongCB.setText(luongCBObj != null ? dfTien.format(luongCBObj) + " đ" : "0 đ");
            lblLuongTL.setText(thucLinhObj != null ? dfTien.format(thucLinhObj) + " đ" : "0 đ");
            Luong luongNV = null;
            List<Luong> l = luongBUS.getAllLuong();
            for (Luong luong : l) {
                if (luong.getMaNV().equals(maNV)) {
                    luongNV = luong;
                    break;
                }
            }
            lblSoCongLam.setText(luongNV != null ? String.valueOf(luongNV.getSoNgayCong()) : "0");
            BigDecimal thuong = BigDecimal.ZERO;
            if (tongThuNhapObj != null && thucLinhObj != null) {
                try {
                    double thucLinh = Double.parseDouble(thucLinhObj.toString());
                    double tongThuNhap = Double.parseDouble(tongThuNhapObj.toString());
                    thuong = BigDecimal.valueOf(tongThuNhap - thucLinh);
                } catch (Exception e) {
                    thuong = BigDecimal.ZERO;
                }
            }
            lblThuong.setText(dfTien.format(thuong) + " đ");
        }
    }//GEN-LAST:event_tblChamCongMouseClicked
    private boolean isLocTheoNgay() {
        return chkTimKiemNgay.isSelected() && txtNgayChamCong.getDate() != null;
    }

    private boolean isLocTheoPhong() {
        PhongBan selectedPB = (PhongBan) cboPhongBan.getSelectedItem();
        return selectedPB != null && !selectedPB.getMaPhong().isEmpty();
    }
    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        java.sql.Date ngay = null;
        if (isLocTheoNgay()) {
            Date ngayUtil = txtNgayChamCong.getDate();
            if (ngayUtil != null) {
                ngay = new java.sql.Date(ngayUtil.getTime());
            }
        }

        PhongBan selectedPB = (PhongBan) cboPhongBan.getSelectedItem();
        String maPhong = null;
        if (isLocTheoPhong() && selectedPB != null && !selectedPB.getMaPhong().isEmpty()) {
            maPhong = selectedPB.getMaPhong();
        }

        List<ChamCongAdmin> list = new ArrayList<>();
        if (ngay != null && maPhong != null) {
            list = chamCongAdminBUS.searchChamCongTheoNgayVaPhong(maPhong, ngay);
        } else if (ngay != null) {
            list = chamCongAdminBUS.searchChamCongTheoNgay(ngay);
            System.out.println("HAHA");
        } else if (maPhong != null) {
            list = chamCongAdminBUS.searchChamCongTheoPhong(maPhong);
            System.out.println("HUHU");
        } else {
            KhoiTaoDuLieu();
            return;
        }
        DefaultTableModel modelCC = new DefaultTableModel();
        modelCC.setColumnIdentifiers(new String[]{
            "Mã CC", "Mã NV", "Họ Tên", "Phòng", "Ngày Làm", "Trạng Thái",
            "Lương CB", "Thực Lĩnh", "Tổng Khấu Trừ", "Tổng Thu Nhập"
        });

        for (ChamCongAdmin cc : list) {
            modelCC.addRow(new Object[]{
                cc.getMaCC(),
                cc.getMaNV(),
                cc.getHoTen(),
                cc.getPhong(),
                cc.getNgayLam(),
                cc.getTrangThai(),
                cc.getLuongCoBan(),
                cc.getThucLinh(),
                cc.getTongKhauTru(),
                cc.getTongThuNhap()
            });
        }

        tblChamCong.setModel(modelCC);

        tblChamCong.getColumnModel().getColumn(6).setMinWidth(0);
        tblChamCong.getColumnModel().getColumn(6).setMaxWidth(0);
        tblChamCong.getColumnModel().getColumn(6).setWidth(0);

        tblChamCong.getColumnModel().getColumn(7).setMinWidth(0);
        tblChamCong.getColumnModel().getColumn(7).setMaxWidth(0);
        tblChamCong.getColumnModel().getColumn(7).setWidth(0);

        tblChamCong.getColumnModel().getColumn(8).setMinWidth(0);
        tblChamCong.getColumnModel().getColumn(8).setMaxWidth(0);
        tblChamCong.getColumnModel().getColumn(8).setWidth(0);

        tblChamCong.getColumnModel().getColumn(9).setMinWidth(0);
        tblChamCong.getColumnModel().getColumn(9).setMaxWidth(0);
        tblChamCong.getColumnModel().getColumn(9).setWidth(0);
    }//GEN-LAST:event_btnLocActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        KhoiTaoDuLieu();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            String maNV = lblMaNV.getText().trim();
            Date ngayUtil = txtNgayLam.getDate();
            String trangThai = (String) cboTrangThai.getSelectedItem();

            if (maNV.isEmpty() || ngayUtil == null || trangThai == null || trangThai.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
                return;
            }

            java.sql.Date ngayLam = new java.sql.Date(ngayUtil.getTime());

            ChamCong cc = new ChamCong();
            cc.setMaNV(maNV);
            cc.setNgayLam(ngayLam);
            cc.setTrangThai(trangThai);
            cc.getGioVao();
            cc.getGioRa();

            boolean kq = chamCongBUS.insert(cc);
            if (kq) {
                JOptionPane.showMessageDialog(this, "Thêm chấm công thành công!");
                int thang = ngayLam.toLocalDate().getMonthValue();
                int nam = ngayLam.toLocalDate().getYear();
                int tongNgayCong = chamCongBUS.countNgayCong(maNV, thang, nam);
                luongBUS.updateSoNgayCong(maNV, thang, nam, tongNgayCong);
                System.out.println(maNV + ngayUtil.toString() + trangThai + tongNgayCong);

            } else {
                JOptionPane.showMessageDialog(this, "Thêm chấm công thất bại! Kiểm tra dữ liệu hoặc nhân viên đã có ngày chấm công này.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tblChamCong.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bản ghi để xóa!");
            return;
        }

        int maCC = Integer.parseInt(tblChamCong.getValueAt(row, 0).toString());
        String maNV = tblChamCong.getValueAt(row, 1).toString();
        java.util.Date ngayLamUtil = (java.util.Date) tblChamCong.getValueAt(row, 4);
        java.sql.Date ngayLam = new java.sql.Date(ngayLamUtil.getTime());
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa bản ghi này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        boolean kq = chamCongBUS.delete(maCC);
        if (kq) {
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
            int thang = ngayLam.toLocalDate().getMonthValue();
            int nam = ngayLam.toLocalDate().getYear();
            int tongNgayCong = chamCongBUS.countNgayCong(maNV, thang, nam);
            luongBUS.updateSoNgayCong(maNV, thang, nam, tongNgayCong);
            KhoiTaoDuLieu();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại!");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = tblChamCong.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bản ghi để sửa!");
            return;
        }
        try {
            int maCC = Integer.parseInt(tblChamCong.getValueAt(row, 0).toString());
            String maNV = tblChamCong.getValueAt(row, 1).toString();
            java.util.Date ngayLamUtil = txtNgayLam.getDate();
            java.sql.Date ngayLam = new java.sql.Date(ngayLamUtil.getTime());
            String trangThai = cboTrangThai.getSelectedItem().toString();
            ChamCong cc = new ChamCong();
            cc.setMaCC(maCC);
            cc.setNgayLam(ngayLam);
            cc.setTrangThai(trangThai);

            boolean kq = chamCongBUS.update(cc);
            if (kq) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                int thang = ngayLam.toLocalDate().getMonthValue();
                int nam = ngayLam.toLocalDate().getYear();
                int tongNgayCong = chamCongBUS.countNgayCong(maNV, thang, nam);
                luongBUS.updateSoNgayCong(maNV, thang, nam, tongNgayCong);
                KhoiTaoDuLieu();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatExcel;
    private javax.swing.JButton btnXuatPDF;
    private javax.swing.JComboBox cboPhongBan;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JCheckBox chkTimKiemNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLuongCB;
    private javax.swing.JLabel lblLuongTL;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblPhongBan;
    private javax.swing.JLabel lblSoCongLam;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblThuong;
    private javax.swing.JTable tblChamCong;
    private com.toedter.calendar.JDateChooser txtNgayChamCong;
    private com.toedter.calendar.JDateChooser txtNgayLam;
    // End of variables declaration//GEN-END:variables

    private void KhoiTaoDuLieu() {
        try {
            List<ChamCongAdmin> list = chamCongAdminBUS.getAllChamCongAdmin();
            DefaultTableModel modelCC = new DefaultTableModel();
            modelCC.setColumnIdentifiers(new String[]{
                "Mã CC", "Mã NV", "Họ Tên", "Phòng", "Ngày Làm", "Trạng Thái",
                "Lương CB", "Thực Lĩnh", "Tổng Khấu Trừ", "Tổng Thu Nhập"
            });

            // Thêm từng bản ghi vào model
            for (ChamCongAdmin cc : list) {
                modelCC.addRow(new Object[]{
                    cc.getMaCC(),
                    cc.getMaNV(),
                    cc.getHoTen(),
                    cc.getPhong(),
                    cc.getNgayLam(),
                    cc.getTrangThai(),
                    cc.getLuongCoBan(),
                    cc.getThucLinh(),
                    cc.getTongKhauTru(),
                    cc.getTongThuNhap()
                });
            }

            // Gán model vào JTable
            tblChamCong.setModel(modelCC);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi load dữ liệu chấm công: " + ex.getMessage());
        }
    }

    private void KhoiTaoCBO() {
        DefaultComboBoxModel<PhongBan> modelPhongBan = new DefaultComboBoxModel<>();
        List<PhongBan> dsPhongBan = pbBUS.getAllPhongBan();
        PhongBan allPhong = new PhongBan(dsPhongBan.get(0).getMaPhong(), "Tất cả", dsPhongBan.get(0).getMoTa());
        allPhong.setMaPhong("");
        modelPhongBan.addElement(allPhong);
        modelPhongBan.addElement(allPhong);
        for (PhongBan pb : dsPhongBan) {
            modelPhongBan.addElement(pb);
        }
        cboPhongBan.setModel(modelPhongBan);
        DefaultComboBoxModel<String> modelTrangThai = new DefaultComboBoxModel<>();
        modelTrangThai.addElement("Đã Chấm Công");
        modelTrangThai.addElement("Chưa Chấm Công");
        modelTrangThai.addElement("Vắng");
        cboTrangThai.setModel(modelTrangThai);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            // Tạo JFrame
            JFrame frame = new JFrame("Quản Lý Chấm Công Admin");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(1000, 700);

            // Thêm panel QLChamCongPanel vào frame
            QLChamCongPanel panel = new QLChamCongPanel();
            frame.setContentPane(panel);

            // Hiển thị frame
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }

}
