/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Admin;

import BUS.LuongBUS;
import BUS.NhanVienBUS;
import BUS.PhongBanBUS;
import javax.swing.DefaultComboBoxModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author PC
 */
public class ThongKePanel extends javax.swing.JPanel {

    PhongBanBUS pbBUS = new PhongBanBUS();
    NhanVienBUS nvBUS = new NhanVienBUS();
    LuongBUS luongBUS = new LuongBUS();

    /**
     * Creates new form ThongKePanel
     */
    public ThongKePanel() {
        initComponents();
        KhoiTaoDuLieu();
        loadThongKe();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTongNV = new javax.swing.JLabel();
        lblSoPB = new javax.swing.JLabel();
        lblQuyLuong = new javax.swing.JLabel();
        btnExcel = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        cboThang = new javax.swing.JComboBox<>();
        cboNam = new javax.swing.JComboBox<>();
        NhanVienPanel = new javax.swing.JPanel();
        QuyLuongPanel = new javax.swing.JPanel();

        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("Tổng Nhân Viên: ");

        jLabel2.setForeground(java.awt.Color.red);
        jLabel2.setText("Số Phòng Ban:");

        jLabel3.setForeground(java.awt.Color.red);
        jLabel3.setText("Quỹ Lương Tháng:");

        lblTongNV.setForeground(java.awt.Color.red);

        lblSoPB.setForeground(java.awt.Color.red);

        lblQuyLuong.setForeground(java.awt.Color.red);

        btnExcel.setText("Xuất Excel");

        btnPDF.setText("Xuất PDF");

        cboThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTongNV, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPDF))
                    .addComponent(lblSoPB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblQuyLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnExcel, btnPDF});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTongNV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPDF)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoPB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuyLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnExcel, btnPDF});

        javax.swing.GroupLayout NhanVienPanelLayout = new javax.swing.GroupLayout(NhanVienPanel);
        NhanVienPanel.setLayout(NhanVienPanelLayout);
        NhanVienPanelLayout.setHorizontalGroup(
            NhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );
        NhanVienPanelLayout.setVerticalGroup(
            NhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout QuyLuongPanelLayout = new javax.swing.GroupLayout(QuyLuongPanel);
        QuyLuongPanel.setLayout(QuyLuongPanelLayout);
        QuyLuongPanelLayout.setHorizontalGroup(
            QuyLuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
        QuyLuongPanelLayout.setVerticalGroup(
            QuyLuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(NhanVienPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QuyLuongPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NhanVienPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuyLuongPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NhanVienPanel;
    private javax.swing.JPanel QuyLuongPanel;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnPDF;
    private javax.swing.JComboBox<String> cboNam;
    private javax.swing.JComboBox<String> cboThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQuyLuong;
    private javax.swing.JLabel lblSoPB;
    private javax.swing.JLabel lblTongNV;
    // End of variables declaration//GEN-END:variables

    private void KhoiTaoDuLieu() {
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        pieDataset.setValue("PB01", 30);
        pieDataset.setValue("PB02", 20);
        pieDataset.setValue("PB03", 15);
        JFreeChart pieChart = ChartFactory.createPieChart("Nhân viên theo phòng ban", pieDataset, true, true, false);
        ChartPanel chartPanelPie = new ChartPanel(pieChart);
        chartPanelPie.setPreferredSize(new java.awt.Dimension(400, 300));

        NhanVienPanel.removeAll();
        NhanVienPanel.setLayout(new java.awt.BorderLayout());
        NhanVienPanel.add(chartPanelPie, java.awt.BorderLayout.CENTER);
        NhanVienPanel.validate();

        // BarChart – Quỹ lương theo phòng ban
        DefaultCategoryDataset barDataset = new DefaultCategoryDataset();
        barDataset.addValue(500000, "PB01", "Tháng 8");
        barDataset.addValue(700000, "PB02", "Tháng 8");
        barDataset.addValue(400000, "PB03", "Tháng 8");
        JFreeChart barChart = ChartFactory.createBarChart("Quỹ lương theo phòng ban", "Phòng ban", "Tiền lương", barDataset);
        ChartPanel chartPanelBar = new ChartPanel(barChart);
        chartPanelBar.setPreferredSize(new java.awt.Dimension(400, 300));

        QuyLuongPanel.removeAll();
        QuyLuongPanel.setLayout(new java.awt.BorderLayout());
        QuyLuongPanel.add(chartPanelBar, java.awt.BorderLayout.CENTER);
        QuyLuongPanel.validate();
        NhanVienPanel.validate();
        DefaultComboBoxModel<String> modelThang = new DefaultComboBoxModel<>();
        for (int m = 1; m <= 12; m++) {

            modelThang.addElement(String.format("%02d", m));
        }
        cboThang.setModel(modelThang);
        int currentMonth = java.time.LocalDate.now().getMonthValue();
        cboThang.setSelectedItem(String.format("%02d", currentMonth));
        DefaultComboBoxModel<String> modelNam = new DefaultComboBoxModel<>();
        int currentYear = java.time.LocalDate.now().getYear();
        int startYear = currentYear - 5;
        int endYear = currentYear + 5;
        for (int y = startYear; y <= endYear; y++) {
            modelNam.addElement(String.valueOf(y));
        }
        cboNam.setModel(modelNam);
        cboNam.setSelectedItem(String.valueOf(currentYear));
        cboThang.addActionListener(e -> loadThongKe());
        cboNam.addActionListener(e -> loadThongKe());
    }

    private void loadThongKe() {
        int soPhong = pbBUS.getSoPhongBan();
        lblSoPB.setText(String.valueOf(soPhong));
        int tongNhanVien = nvBUS.demTongNhanVien();
        lblTongNV.setText(String.valueOf(tongNhanVien));
        int thang = cboThang.getSelectedIndex() + 1;
        int nam = Integer.parseInt(String.valueOf(cboNam.getSelectedItem()));
        double tongLuong = luongBUS.getTongLuongThucLinh(thang, nam);
        lblQuyLuong.setText(String.format("%,.0f", tongLuong));
    }
}
